### PR TITLE
Add Travis CI configuration.

### PR DESCRIPTION
**Pull request by lijunle**
Use Travis virtual screen to run test in Chromium: http://stackoverflow.com/a/25661593/1436671

### CODE REVIEW

**Comment by lijunle** [comment]
@dustingetz To enable Travis, you also need to enable the project in Travis home page. See [its docs](http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A).

**Comment by dustingetz** [comment]
Thank you! will merge soon

**Comment by lijunle** [comment]
@dustingetz could you like to merge this? A CI build is important to keep the code quality. :white_check_mark:

**Comment by dustingetz** [comment]
If I click merge right now, what will happen? I haven't used this feature before

**Comment by lijunle** [comment]
Nothing happens.

You need to go the http://travis-ci.org to enable your repo. After that, when new commit push to this repo, or somebody send a PR, Travis will trigger a build to run the tests.

Here is [an successful example](https://travis-ci.org/lijunle/react-cursor/builds/75410180). You can click on [one job](https://travis-ci.org/lijunle/react-cursor/jobs/75410181) to see the console log - all tests are run and green. :smiley:

**Comment by lijunle** [comment]
@damassi are you going to enable it now? If enabled, I can re-push my another RP to trigger a build - you can see some interesting things. :)

**Comment by dustingetz** [comment]
It's enabled, go ahead and re-push

**Comment by lijunle** [comment]
Finally, the failure is resolved.

Look on the [RP page](https://github.com/dustingetz/react-cursor/pull/69), you will find there is some :x: and :white_check_mark: , which indicate that commit is passing the test or not. You can click on those icons to check the detail build output.

The Travis build ensure the RP won't break the test accidentally. Enjoy it. :ghost:

**Pull request merged**
