### PR TITLE
Add Cursors support for dissoc

### PR DESCRIPTION
**Pull request by danielmiladinov**

### CODE REVIEW

**Comment by dustingetz** [comment]
Thanks this is great. It also needs to work for maps - but that can be done in a separate pass. Do you want to take a whack at that or should I just merge this?

**Comment by dustingetz** [comment]
I'm also thinking the remove fn should be pushed into the update-in dependency. And that remove fn should work on key or index. But let me know if I should just merge this for now.

**Comment by danielmiladinov** [comment]
I can do both, in this PR.

**Comment by danielmiladinov** [comment]
Actually, moving the remove fn to update-in will be a separate pr to update-in

**Pull request merged**
