### PR TITLE
Avoid unnecessary renders

### PR DESCRIPTION
**Pull request by danielmiladinov**
This works for non-function values passed to `update`, updating with function values will need more thought.

Happy to receive feedback on what I have so far.

### CODE REVIEW

**Comment by dustingetz** [comment]
Why doesn't it work with functions? (We don't support functions, but this code looks like it would work)

**Comment by danielmiladinov** [comment]
Updated the PR, now it handles both function and non-function cases of `nextUpdate`.
Could probably use some cleanup, but the basic idea is in place.

**Comment by dustingetz** [comment]
This looks merge-able to me, did we have a reason for not merging this yet?

**Comment by dustingetz** [comment]
I merged this PR into 2.0. The final result took more work due to the 2.0 changes (decoupling from react) impacting this issue in unexpected ways.

**Pull request merged**
