### PR TITLE
Avoid internal api

### LINKED ISSUE #43: Avoid using React internal APIs.
In the [`update` method](https://github.com/dustingetz/react-cursor/blob/master/src/Cursor.js#L40), you are using `cmp._reactInternalInstance._pendingStateQueue` to get the latest state.

Actually, React provide a `setState` override accepting function as the first argument to access the latest state. (Its logic is [here](https://github.com/facebook/react/blob/6a92179d6fd6d7c4097f6310a7cefb2c0651287f/src/renderers/shared/reconciler/ReactCompositeComponent.js#L604))

```js
function update(cmp, path, operation, nextValue) {
  this.setState(function (state) {
    if (path.length > 0) {
      return React.addons.update(
        state,
        path.concat(operation).reduceRight(util.unDeref, nextValue)
      );
    } else if (path.length === 0) {
      return nextValue;
    }
  });
}
```

*PS.* the current implementation prohibits the root component has its own state. Otherwise, the latest state in queue might be a partial object and not meet the unDeref operations.

### PR DESCRIPTION
**Pull request by lijunle**
Resolve #43

### CODE REVIEW

**Comment by danielmiladinov** [comment]
I'm not sure if it's safe to merge this yet. By advancing the dependency to react 0.13, we lose access to the internal `_pendingState` property we were relying on for the behavior of `Cursor.pendingValue()`. React 0.13 also changed how batched calls to `setState` are handled, so we should examine the ramifications of these changes a little more closely. Thoughts, @dustingetz ?

**Comment by lijunle** [comment]
I am updating React in test code and the example code.

if somebody uses React 0.13 + the current react-cursor, he will get a failure on `pendingValue` too. That is why I open an issue to suggest avoid internal APIs. Using such APIs are *dangerous*, it is *safe* to avoid them.

Reading the reason that providing `pendingValue` property in this [post](https://github.com/facebook/react/issues/122), I think that can be resolved using `setState(func)` override.

**Comment by lijunle** [comment]
One more thing, the way that `pendingValue` work is, this package manage the full state of the components and the `setState` call. So, the `_pendingValue` must be a full state object passed from [`update` function](https://github.com/dustingetz/react-cursor/blob/master/src/Cursor.js#L50).

After `_pendingValue` internal API is removed as of 0.13. This package could do the same thing - store the state under a *Map* or *WeakMap* internally **synchronously**. Then, in the `pendingValue` function, return that object.

Because this process it **synchronous** (not like `setState` which is asynchronous operation), the `pendingValue` works fine.

**Comment by dustingetz** [comment]
So to loop back through, we followed this PR and removed pendingValue. We also exposed the new setState api in react 13 so the cursor updater methods can take either a partial object value (old api) or an updater function (better api introduced in react 13).

I want to think a little more about cursor.apply before fixing the failing test.

**Comment by lijunle** [comment]
@dustingetz I like your new API, which is so cool.

I don't get the meaning of fixing the failing test. Are you meaning my comment in the code? The one to add unit test to cover the new API?

**Comment by lijunle** [comment]
@dustingetz I find your failing test case finally. Let us open another issue for this.

**Pull request merged**
